### ISSUE TITLE
netbeans ignorable files commited to git

### ISSUE THREAD

**Issue by kinggoesgaming** [Zixiken/DimDoors#16]
Thanks to @Robijnvogel the `.nb-gradle` folder and `.nb-gradle-properties` is in git.

simple solution:
* move  the folder and the file out of the project temporarily
* add `.nb-gradle/` and `.nb-gradle-properties` in `.gitignore`.
* commit
* move the folder and file back.
* push
* ...
* profit

**Comment by Robijnvogel** [comment]
Thank you :)

**Comment by Robijnvogel** [comment]
Well whataya know. That actually worked. :D
