### ISSUE TITLE
[Suggestion] Instead of creating fresh dimensions for each pocket, instead use single dimension to house every pocket dimension

### ISSUE THREAD

**Issue by UndeadZeratul** [Zixiken/DimDoors#8]
Taken from [here](https://github.com/CannibalVox/DimDoors/issues/54).

Since you're in the process of porting the mod to 1.9/1.10/etc. would it make sense to also make changes to the mod?

I was wondering if it made more sense for pocket dimensions, pocket dungeons, etc. to all exist within their own designated chunks within the same dimension, instead of the current process of giving each their own private dimension.  There were some concerns about this concept in the other thread, regarding the mod's own lore, blocks that border the pocket dimensions being breakable/replaceable/etc.  I've also thought of a few more things since originally posting that issue that might be weird with a change like this, including the monoliths surrounding a dungeon piece that is next to a personal pocket dimension or dungeon that doesn't have them, or being able to teleport between any pocket dimension with various mods much easier since the pocket dimensions could be physically reachable now.

Either way, since it seems this is the updated repo I figured I'd link my original issue here for visibility.

**Comment by kinggoesgaming** [comment]
@UndeadZeratul 

> blocks that border the pocket dimensions being breakable/replaceable/etc

Easy fix... dont make the border blocks available as droppable items. and event checks if a player/ natural event breaks with creative/ command block cancel the event

**Comment by Robijnvogel** [comment]
We are currently working on this.

**Comment by Robijnvogel** [comment]
Because of practical reasons (in anticipation of the disappearing of Zixiken), we have continued working on this mod [over here](https://github.com/DimensionalDevelopment/DimDoors/).

Fixing this issue has been one of the main goals of our re-design of the mod, so I think this issue can be closed. :)
