### ISSUE TITLE
Compiling mod for 1.10.2

### ISSUE THREAD

**Issue by badhaloninja** [Zixiken/DimDoors#9]
Im having trouble compiling the mod it keeps saying that it can't find the symbol, "BlockPos" in https://github.com/Zixiken/DimDoors/blob/1.10/src/main/java/com/zixiken/dimdoors/items/BaseItemDoor.java

if someone could help me or give me the compiled mod for 1.10.2-12.18.2.2105 that would be great.

**Comment by Waterpicker** [comment]
It's 1.8.9. Feel free to go with updating that branch to 1.10.2 if you wish however.

**Comment by badhaloninja** [comment]
that explains a lot actually thanks

**Comment by Waterpicker** [comment]
Your welcome.
